---
- name: Configure AWS CLI
  hosts: localhost
  become: yes
  tasks:
   - name: Ensure AWS CLI is installed
     package:
      name: awscli
      state: present
   
   - name: Create AWS credentials directory
     file:
      path: "{{ ansible_env.HOME }}/.aws"
      state: directory
      mode: '0700'
   
   - name: Configure AWS credentials
     copy:
      dest: "{{ ansible_env.HOME }}/.aws/credentials"
      content: |
       [default]
       aws_access_key_id = {{ aws_access_key_id }}  # Replace with your actual AWS Access Key ID
       aws_secret_access_key = {{ aws_secret_access_key }}  # Replace with your actual AWS Secret Access Key
      mode: '0600'
   
   - name: Configure AWS config
     copy:
      dest: "{{ ansible_env.HOME }}/.aws/config"
      content: |
       [default]
       region = {{ aws_region }}  # Replace with your desired AWS region (e.g., us-east-1)
       output = json
      mode: '0600'
  
  vars:
   aws_access_key_id: "{{ lookup('aws_ssm', 'access_key_id', region='us-east-1' ) }}"  # Replace with your actual AWS Access Key ID
   aws_secret_access_key: "{{ lookup('aws_ssm', 'secret_access_key', region='us-east-1' ) }}"  # Replace with your actual AWS Secret Access Key
   aws_region: "us-east-1"  # Replace with your desired AWS region (e.g., us-east-1)
